### ISSUE TITLE
Code uses deprecated methods from CBOR library

### ISSUE THREAD

**Issue by LudwigSeitz** [cose-wg/COSE-JAVA#23]
In Message.DecodeFromBytes() the deprecated method CBORObject.getOutermostTag() is used. The author of that library has removed that functionality in the latest version and recommends to use getMostOuterTag() instead.

**Comment by jimsch** [comment]
The function getOuterMostTag does not appear to have been deprecated as of release 2.4.1  The suggested new function is not in the jar on Maven.

**Comment by jimsch** [comment]
Based on comment from PeterO, this is going to be deprecated in V 3.0 and thus cannot be done yet.
