### ISSUE TITLE
Attribute class not visible

### ISSUE THREAD

**Issue by LudwigSeitz** [cose-wg/COSE-JAVA#34]
Since the Attribute class is now not "public", code like this breaks:

MAC0Message coseM0 = new MAC0Message();
coseM0.addAttribute(HeaderKeys.Algorithm, ctx.getAlg(), 
					Attribute.ProtectedAttributes);    <---- This breaks

Since Attribute is not visible at that level (some other class file), I cannot refer to Attribute.ProtectedAttributes

**Comment by LudwigSeitz** [comment]
You can use Message.PROTECTED and Message.UNPROTECTED instead, not sure if this is the intention, but it should be documented and from a stylistic viewpoint, I'd recommend moving those constants up to the Message class

**Comment by jimsch** [comment]
I don't know to be happy or sad that the unit tests did not see this.  I was just trying to hide more things when making Attribute hidden.   I think that Attribute.PROTECTED makes more sense because it can be used with things like recipients which aren't derived from messages.
