### ISSUE TITLE
Get java.security.PublicKey and java.security.PrivateKey from OneKey

### ISSUE THREAD

**Issue by LudwigSeitz** [cose-wg/COSE-JAVA#39]
For using the data in a OneKey object in other (non-COSE) classes (e.g. a DTLS handshake) it would be nice to have a method that returns a java.security.PublicKey and java.security.PrivateKey.

**Comment by jimsch** [comment]
Does this just expose the key fields or is it supposed to provide crypto operations as well?  From what I can see it just exposes the fields.

**Comment by LudwigSeitz** [comment]
It doesn't provide any crypto operations, but it is e.g. used in the DTLS implementation Scandium
https://github.com/eclipse/californium/blob/master/demo-apps/cf-secure/src/main/java/org/eclipse/californium/examples/SecureClient.java

**Comment by LudwigSeitz** [comment]
... to provide the key fields to the DTLS code.

**Comment by jimsch** [comment]
I hope that at present you only need ECDH and ECDSA keys for the NIST curves as the classes for the new Edwards curves don't exist.
