### ISSUE TITLE
Think about storing a JAVA key as part of the OneKey structure

### ISSUE THREAD

**Issue by jimsch** [cose-wg/COSE-JAVA#54]
It might become efficent to allow for the OneKey structure to store a pointer to the JAVA key object that it creates the first time that it needs to do an import operation.  This would mean that this code would not need to be run a second time.  The down side is that the key information is stored in memory twice.

**Comment by karthikfbk** [comment]
Is it possible to convert Java EC Key (java.security.PrivateKey, java.security.PublicKey) to OneKey Structure with curve type EC2 ?

**Comment by jimsch** [comment]
We now store the keys as part of the structure since the re-write to be Java Crypto provider based.

**Comment by jimsch** [comment]
@karthikfbk  
Preliminary version of this is now done in a branch that still needs to get more testing before integration.  If you want to look the branch is at https://github.com/jimsch/COSE-JAVA/tree/OneKeyFromPublicKey

**Comment by jimsch** [comment]
Fixed by #73 - will be in the next drop.
