### ISSUE TITLE
Consider replacing Exception in Recipient class with NoSuchAlgorithmException

### ISSUE THREAD

**Issue by LudwigSeitz** [cose-wg/COSE-JAVA#55]
In the Recipient class in the  getKey() method, java.lang.Exception  is thrown for the algorithms       
   AES_KW_128,  AES_KW_192, and AES_KW_256

This masks the other exceptions, since Exception is a superclass of all other exceptions.
I would suggest to use java.security.NoSuchAlgorithmException instead.

From the description: "This exception is thrown when a particular cryptographic algorithm is requested but is not available in the environment."

**Comment by jimsch** [comment]
Just fixed the code so that the missing code was there.  The wrong exception was there because I missed putting the correct code in.

**Comment by jimsch** [comment]
See drop 0.9.6

**Comment by LudwigSeitz** [comment]
getKey() and encrypt() still throw that exception
