### ISSUE TITLE
Adding SecurityProvider for AES_CCM Encrypt

### ISSUE THREAD

**Issue by vikram919** [cose-wg/COSE-JAVA#71]
Currently COSE-JAVA on using AES_CCM Encrypt modes for ex; Algorithm AES_CCM_64_64_128 throws an exception no provider for the Algorithm. why don't we add below line
`Security.addProvider(new BouncyCastleProvider());`  in `EncryptCommon` class for `AES_CCM_Encrypt()` function.

**Comment by LudwigSeitz** [comment]
Jim is trying to get away from having a dependency on Bouncy Castle, is there a native provider from the Java distros we can use instead?

**Comment by vikram919** [comment]
@LudwigSeitz 
Currently No. https://docs.oracle.com/javase/9/docs/api/javax/crypto/Cipher.html As far as I study only GCM (without padding) and CBC are supported modes in AES.

**Comment by jimsch** [comment]
It makes sense to put information in the readme on the home page for the project on the fact that providers are needed and how to install them, but forcing to a specific provider is something that I am trying to avoid at this point.

**Comment by vikram919** [comment]
> It makes sense to put information in the readme on the home page for the project on the fact that providers are needed and how to install them

Adding this to readme helps, users are free to choose providers on their own.
