### ISSUE TITLE
Parameter in generateOkpKey called from generateKey

### ISSUE THREAD

**Issue by rikard-sics** [cose-wg/COSE-JAVA#86]
I am continuing an implementation of Group OSCORE in Java. I have been working with further details regarding the countersignatures and keys.

I believe the line referenced below should rather be:
`returnThis = generateOkpKey("Ed25519", KeyKeys.OKP_Ed25519); `

https://github.com/cose-wg/COSE-JAVA/blob/f972b11ab4c9a18f911bc49a15225a6951cf6f63/src/main/java/COSE/OneKey.java#L433

Then it matches the switch statement in generateOkpKey.

**Comment by jimsch** [comment]
Fixed in 0.9.10
