### ISSUE TITLE
RSA support

### ISSUE THREAD

**Issue by fmonniot** [cose-wg/COSE-JAVA#94]
Hello there,

First, thank you for providing an option for the JVM World. This is much appreciated

The readme state that RSA (RFC 8230) is not currently implemented. Is there any particular reason why that is ?  And if the reason is time, how interested would you be for a contribution adding support for the RSASSA-PSS family ?

**Comment by jimsch** [comment]
Be my guest in terms of getting it running.  I started it a long time ago and just dropped because I wasn't interested enough.  Look in my personal repository for the RSA branch of this.  It may be almost done I haven't looked at it in a long time

**Comment by fmonniot** [comment]
#95 got merged (there is no support for RSA encryption, only RSA signatures), but I'll consider this issue fixed for my case.
