### ISSUE TITLE
Example using the package

### ISSUE THREAD

**Issue by vukgogo** [cose-wg/COSE-JAVA#98]
Hey, first thanks for this development in the Java world. I know COSE is very scarce especially with documentation and examples. I did see a few items in the Wiki of how to possibly sign the message and things like that. My question is for example how one would construct this type of object using the package:

![](https://cdn-images-1.medium.com/max/800/1*RYFNVMQeoE6sbxbWB1LSrw.png)

Would something like this make sense?:

        CBORObject cborObject = CBORObject.NewMap();
        cborObject.Add("payload", "This is the content.");

        byte[] cborBytes = cborObject.EncodeToBytes();

        SignMessage msg = new SignMessage();
        msg.SetContent(cborBytes);

        Signer signer = new Signer();

        OneKey oneKey = new OneKey(publicKey, privateKey);

        signer.setKey(oneKey);
        signer.addAttribute(HeaderKeys.Algorithm, AlgorithmID.ECDSA_256.AsCBOR(), Attribute.PROTECTED);
        signer.addAttribute(HeaderKeys.KID, CBORObject.FromObject("11"), Attribute.UNPROTECTED);

        msg.AddSigner(signer);
        msg.sign();

        return msg.EncodeToBytes();

I don't know if I'm missing part of the '/ signature /' of the COSE object or not code wise, also from the image the first two protected/unprotected headers, are they automatically put in or how would you include them as well? Any help/guidance would be appreciated. Thanks!

**Comment by jimsch** [comment]
The code to set the content is not going to be what you want.  The rest looks fine.  

msg.SetContent("This is the content.") ;

or 

msg.SetContent(CBORObject.FromObject("This is the content.");

Your example would end up with the content of "{\"payroll\":\"This is the content.\"}"

All of the encoding about the attribute fields as well as the signature field are all automatically built.  

The most complete look at how things work is going to be the regression test file.  But yes, I really should be doing some documentation at some point.

**Comment by vukgogo** [comment]
Alright sweet! Again thank you so much!
